version: "3.5"

services:
  postgres:
    container_name: fruity-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - fruity_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - fruity-network

  go-ecommerce:
    container_name: fruity-go
    build: ./
    env_file: .env.production
    ports:
      - "3000:3000"
    networks:
      - fruity-network
    depends_on:
      - postgres
    restart: always

volumes:
  fruity_data:

networks:
  fruity-network: