name: golang-pipeline
on: push
env:
  PORT: 3000
  DEBUG: true
  ENV: test
  JWT_SECRET_KEY: xinchaominhlasecretkey
          
jobs:
  test:
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test ./...

  deploy:
      runs-on: ubuntu-latest
      needs: test
      if: github.ref == 'refs/heads/master'
      steps:
        - name: Execute SSH commmands on remote server
          uses: JimCronqvist/action-ssh@master
          with:
            hosts: 'fruity@100.26.42.214'
            privateKey: ${{ secrets.KEY }}
            script: cd /home/fruity/go-fruity && git reset --hard origin/master && git pull && docker-compose up -d --build

        
