name: golang-pipeline
on: push
env:
  PORT: 3000
  DEBUG: true
  ENV: test
  JWT_SECRET_KEY: xinchaominhlasecretkey
          
jobs:
  test:
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test ./...

  deploy:
      runs-on: ubuntu-latest
      needs: test
      if: github.ref == 'refs/heads/master'
      steps:
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            command_timeout: 200m
            script: |
                cd /home/fruity/go-fruity
                git reset --hard origin/master
                git pull
                docker-compose up -d --build

        
