name: golang-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
    steps:
      - name: Create env file
        run: |
          touch .env
          echo "PORT=3000" >> .env
          echo "ENV=test" >> .env
          echo "DEBUG=true" >> .env
          cat .env
          echo $GITHUB_WORKSPACE
        working-directory: "${GITHUB_WORKSPACE}"


      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test ./...

        
